stjudecloud/docs

- source/guides/tools/pecan-pie/faq.rst
Please approve as soon as you can. I couldn't commit directly - perhaps I'm missing the proper permissions.
thanks.
> Updated 20mb -> 4GB file size limit spec for PecanPIE.

- source/guides/tools/pecan-pie/index.rst
- source/guides/tools/pecan-pie/standalone.rst
PIE documentation update for standalone dnanexus pipeline usage
> Pie standalone pipelines

- docs/guides/data/types-of-data.md
Added information about how the Somatic VCF files were produced as requested by one of our end users.
> Added Somatic VCF file information to "Types of Data".

- docs/guides/tools/cis-x.md
These arguments were added in https://github.com/stjude/cis-x/commit/58f66b7d77a389d0dace0de351eb7e0e8e87b0fa.
> cis-x: Add inputs for marker filters

- docs/guides/tools/pecan-pie.md
Pecan PIE gene list section updated to match with the updates on the
website. "Germline reviewable" list is referred to as "Cancer
predispostion" according to JZ's wishes.
> Pecan PIE doc updates.

- docs/guides/data/metadata.md
- docs/guides/data/run-your-tools.md
- docs/guides/data/types-of-data.md
- mkdocs-material/src/base.html
- mkdocs.yml
Added CNV files description to Data Types page. Added page for metadata in SAMPLE_INFO.txt file. Added Adobe Analytics code bit in base. In progress editing Run Your Own Tools page but did not yet add link in mkdocs.yml.
> Misc doc updates

- docs/guides/data/data-overview.md
- docs/guides/data/metadata.md
- mkdocs.yml
Various updates to the docs as I ran through them.
> Scrub-through 1/16/19

- docs/guides/tools/mutational-spectrum.md
> mutspec: Add getting started

- docs/guides/tools/cis-x.md
> cis-x: Add getting started

- mkdocs.yml
Clicking on the edit pencil doesn't work.
> Fixed edit link

- docs/guides/data/data-request.md
- docs/guides/tools/neoepitope.md
-On the Making a Data Request page, created subsections under the Requesting Data secdtion to more clearly exposure the DAA process to the user.
-Removed "To do" note on NeoepitopePred page and made soem small grammatical edits. Will update page as needed when I hear back from Ti-Cheng.
-broken links to excel an text sample sheet work on local host, but not production. Arthur looked into this, and it seems to be an issue urls (i.e. something for AEM team to investigate and fix).
> Changes based on suggestions from Livia

- docs/guides/tools/pecan-pie.md
This is a request from Jinghui to update the PIE documentation page to reflect the recent Genome Research publication.
> - updated PeCanPIE publication to reflect Genome Research 2019 paper

- docs/guides/forms/how-to-fill-out-DAA.md
Adapted/highly edited from a successful SJLIFE and PCGP use.
> Added Contemplated Use Example

- docs/guides/forms/how-to-fill-out-DAA.md
> Simulated Contemplated Use

- docs/guides/data/data-request.md
> Spelling error

- docs/guides/tools/rapid-rnaseq.md
Adding a link to the FAQ instructions on running commands in batch at Jinghui's request.
> Adding link to FAQ for batch submission.

- docs/guides/covid-19.md
- docs/guides/data/uploading-data-from-st-jude-hpc-to-dnanexus.md
- mkdocs.yml
This adds a guide on how to upload data from St. Jude `hpc` to DNAnexus.
> guides/data: Add "Uploading Data from St. Jude HPC to DNAnexus"

- docs/guides/genomics-platform/analyzing-data/cis-x.md
This syncs the inputs between cis-X 1.5.0 and the DNAnexus app (1.5.0-2).
> guides/cis-x: Update to cis-X 1.5.0-2

- docs/guides/genomics-platform/analyzing-data/rnaseq-expression-classification.md
- docs/guides/genomics-platform/analyzing-data/running-sj-workflows.md
- docs/guides/genomics-platform/faq.md
I added an FAQ question back into the Genomics Platform FAQ, and also edited so that all of the workflows are listed on the page with them listed with links.
> Adding faq questions back

- docs/guides/genomics-platform/analyzing-data/sequencerr.md
Added details regarding publication and removed notes to the reviewers
> Sequencerr
